-- Problem 69: Supply Chain Risk Assessment and Mitigation Analysis
-- Level: Complex
-- ============================================================

-- PROBLEM STATEMENT:
-- Write a query to assess supply chain risks and identify mitigation strategies based on supplier dependency and geographic concentration.

-- ============================================================
-- SOLUTION:
-- ============================================================

WITH SupplierDependency AS (SELECT s.supplierId, s.companyName AS supplierName, s.country AS supplierCountry, COUNT(p.productId) AS productsSupplied, SUM(p.unitsInStock * p.unitPrice) AS inventoryValue, SUM(od.quantity) AS totalDemand FROM Supplier s JOIN Product p ON s.supplierId = p.supplierId LEFT JOIN OrderDetail od ON p.productId = od.productId GROUP BY s.supplierId, s.companyName, s.country), CategoryRisk AS (SELECT c.categoryId, c.categoryName, COUNT(DISTINCT p.supplierId) AS supplierCount, COUNT(p.productId) AS productCount, AVG(sd.inventoryValue) AS avgInventoryValue FROM Category c JOIN Product p ON c.categoryId = p.categoryId JOIN SupplierDependency sd ON p.supplierId = sd.supplierId GROUP BY c.categoryId, c.categoryName), GeographicConcentration AS (SELECT sd.supplierCountry, COUNT(sd.supplierId) AS supplierCount, SUM(sd.productsSupplied) AS totalProducts, SUM(sd.inventoryValue) AS totalInventoryValue, COUNT(DISTINCT c.categoryId) AS categoriesServed FROM SupplierDependency sd JOIN Product p ON sd.supplierId = p.supplierId JOIN Category c ON p.categoryId = c.categoryId GROUP BY sd.supplierCountry), RiskAssessment AS (SELECT sd.supplierId, sd.supplierName, sd.supplierCountry, sd.productsSupplied, sd.inventoryValue, sd.totalDemand, gc.supplierCount AS countrySuppliers, cr.supplierCount AS categorySuppliers, CASE WHEN sd.productsSupplied > 10 THEN 'High Dependency' WHEN sd.productsSupplied > 5 THEN 'Medium Dependency' ELSE 'Low Dependency' END AS dependencyRisk, CASE WHEN gc.supplierCount <= 2 THEN 'High Geographic Risk' WHEN gc.supplierCount <= 5 THEN 'Medium Geographic Risk' ELSE 'Low Geographic Risk' END AS geographicRisk FROM SupplierDependency sd JOIN GeographicConcentration gc ON sd.supplierCountry = gc.supplierCountry JOIN Product p ON sd.supplierId = p.supplierId JOIN CategoryRisk cr ON p.categoryId = cr.categoryId), RiskMitigation AS (SELECT dependencyRisk, geographicRisk, COUNT(*) AS supplierCount, AVG(inventoryValue) AS avgInventoryValue, SUM(totalDemand) AS totalDemand, CASE WHEN dependencyRisk = 'High Dependency' AND geographicRisk = 'High Geographic Risk' THEN 'Critical - Diversify Immediately' WHEN dependencyRisk = 'High Dependency' OR geographicRisk = 'High Geographic Risk' THEN 'High - Plan Diversification' WHEN dependencyRisk = 'Medium Dependency' AND geographicRisk = 'Medium Geographic Risk' THEN 'Medium - Monitor Closely' ELSE 'Low - Maintain Current Strategy' END AS mitigationStrategy FROM RiskAssessment GROUP BY dependencyRisk, geographicRisk) SELECT mitigationStrategy, supplierCount, avgInventoryValue, totalDemand, (totalDemand / SUM(totalDemand) OVER ()) * 100 AS demandPercentage FROM RiskMitigation ORDER BY FIELD(mitigationStrategy, 'Critical - Diversify Immediately', 'High - Plan Diversification', 'Medium - Monitor Closely', 'Low - Maintain Current Strategy');
