-- Problem 90: Advanced Financial Analysis and Forecasting
-- Level: Complex
-- ============================================================

-- PROBLEM STATEMENT:
-- Write a query to perform comprehensive financial analysis including cash flow projections and profitability forecasting.

-- ============================================================
-- SOLUTION:
-- ============================================================

WITH MonthlyFinancials AS (SELECT DATE_FORMAT(s.orderDate, '%Y-%m') AS month, SUM(od.quantity * od.unitPrice * (1 - od.discount)) AS gross_revenue, SUM(od.quantity * od.unitPrice * 0.4) AS estimated_cogs, SUM(s.freight) AS shipping_costs, COUNT(DISTINCT s.orderId) AS order_count, COUNT(DISTINCT s.custId) AS customer_count FROM SalesOrder s JOIN OrderDetail od ON s.orderId = od.orderId WHERE s.orderDate >= DATE_SUB(CURDATE(), INTERVAL 24 MONTH) GROUP BY DATE_FORMAT(s.orderDate, '%Y-%m')), ProfitabilityAnalysis AS (SELECT month, gross_revenue, estimated_cogs, shipping_costs, (gross_revenue - estimated_cogs - shipping_costs) AS net_profit, (gross_revenue - estimated_cogs - shipping_costs) / NULLIF(gross_revenue, 0) * 100 AS profit_margin_pct, order_count, customer_count, gross_revenue / NULLIF(customer_count, 0) AS revenue_per_customer FROM MonthlyFinancials), TrendAnalysis AS (SELECT month, net_profit, profit_margin_pct, revenue_per_customer, LAG(net_profit, 12) OVER (ORDER BY month) AS profit_12m_ago, LAG(profit_margin_pct, 12) OVER (ORDER BY month) AS margin_12m_ago, AVG(net_profit) OVER (ORDER BY month ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS profit_12m_avg FROM ProfitabilityAnalysis), FinancialProjections AS (SELECT month, net_profit, profit_margin_pct, profit_12m_avg, CASE WHEN profit_12m_ago IS NOT NULL THEN ((net_profit - profit_12m_ago) / NULLIF(profit_12m_ago, 0) * 100) ELSE NULL END AS yoy_profit_growth, profit_12m_avg * 1.05 AS conservative_forecast, profit_12m_avg * 1.15 AS optimistic_forecast FROM TrendAnalysis WHERE month >= DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 12 MONTH), '%Y-%m')), CashFlowProjection AS (SELECT 'Current Month' AS period, AVG(net_profit) AS projected_cash_flow FROM FinancialProjections WHERE month = DATE_FORMAT(CURDATE(), '%Y-%m') UNION ALL SELECT 'Next 3 Months', AVG(conservative_forecast) * 3 FROM FinancialProjections WHERE month >= DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 3 MONTH), '%Y-%m') UNION ALL SELECT 'Next 6 Months', AVG(optimistic_forecast) * 6 FROM FinancialProjections WHERE month >= DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 6 MONTH), '%Y-%m')) SELECT period, FORMAT(projected_cash_flow, 2) AS projected_cash_flow FROM CashFlowProjection;
